[SPIR-V] Support arrays of RWStructuredBuffers
microsoft/DirectXShaderCompiler pull request #4663
Opened 2022-09-16 08:04 UTC by cassiebeckley

I'm not confident this generates the correct code in all cases, so I'd appreciate it if there are any suggestions.

Fixes #3281

2022-09-16 15:24 UTC, vettoreldaniele requested changes
I see two problems with this:
1) The following breaks with `-fspv-flatten-resource-arrays`:
```
RWStructuredBuffer<float4>   localSBuffer = MyRWSBuffer[index];
localSBuffer[0] = 3.0f;
```
```
warning: cannot find the associated counter variable
    RWStructuredBuffer<float4>   localSBuffer = MyRWSBuffer[index];
                                                ^
fatal error: failed to legalize SPIR-V: Variable cannot be replaced: invalid index
  %52 = OpAccessChain %_ptr_Uniform_type_RWStructuredBuffer_v4float %MyRWSBuffer %29
```

2) `MyRWSBuffer[index].IncrementCounter()` correctly generates an error, but the following does not and instead loads an undef value for the non-existent counter variable:
```
RWStructuredBuffer<float4> localSBuffer = MyRWSBuffer[index];
localSBuffer.IncrementCounter();
```

2022-09-18 21:53 UTC, Ipotrick commented
Id love to have this merged. This would make my hlsl api much nicer.

2022-11-24 03:18 UTC, GabeRundlett commented
Is there a reason this was not merged?

2022-11-24 15:54 UTC, vettoreldaniele commented
There are still outstanding comments. @cassiebeckley PTAL when you have a chance. 

I'm ok with the `-fspv-flatten-resource-arrays` behavior being fixed in a follow-up PR , but the problem with the non-existent counter variable should be fixed before this is merged.

2022-12-05 17:54 UTC, cassiebeckley commented
Sorry for the slow response on this, things have been busy. I'll try to get to this by the end of the week

2022-12-09 22:03 UTC, Ipotrick commented
Thank you!

2022-12-12 19:16 UTC, cassiebeckley commented
Quick update: I did make some progress on this, but I'm still working on making sure the correct error messages show up in the correct situations

2023-02-08 07:11 UTC, cshenton commented
This would be amazing to have for bindless workflows!

2023-02-14 13:37 UTC, cassiebeckley commented
Added a new commit that prevents counters from being created from an array subscript expression, which should fix issue 1. There are some tricky situations which should probably also result in errors that I don't know how to fix - for example, a counter is always created for any buffer returned from a function call. This seems difficult to detect statically - the return value of the function is effectively the buffer + the counter, and the function could have a branch where it either returns a buffer from an array, or a buffer that is not from an array.

As for issue 2, I'll create a tracking issue to follow up.

2023-02-14 14:46 UTC, s-perron commented
RWStructuredBuffer<float4> localSBuffer = MyRWSBuffer[index];
localSBuffer.IncrementCounter();

2023-02-14 14:52 UTC, s-perron commented
> As for issue 2, I'll create a tracking issue to follow up.

We should discuss this. We should not give a partially working feature until we have a design to make it fully functional. Something like issue 2 is a clear bug that would be nearly impossible to debug. Is there a design doc for this?

2023-02-14 17:12 UTC, cassiebeckley commented
(I mixed up issue 1 and 2 in my comment, fixed it)

2023-02-14 17:16 UTC, s-perron commented
> (I mixed up issue 1 and 2 in my comment, fixed it)

Cool, what is the error message?

2023-02-14 17:20 UTC, cassiebeckley commented
At the moment, 

```
arr.hlsl:5:12: fatal error: cannot find the associated counter variable
    return localSBuffer.IncrementCounter();
           ^
```

2025-05-23 20:52 UTC, closed without merging