Error on diff blob versions part 1
microsoft/DirectXShaderCompiler pull request #5378
Opened 2023-06-29 21:16 UTC by bob80905

This PR is the first of several to prevent libraries of different compiler versions from linking together. This first PR implements adding the compiler version information into the library blob itself, to allow for comparison later.
A test has been added to verify that the part exists in the container.

2023-06-30 22:02 UTC, tex3d requested changes

2023-06-30 22:02 UTC, tex3d commented on tools/clang/unittests/HLSL/DxilContainerTest.cpp
> +// with SM >= 6.8
Should change comment that says "`with SM >= 6.8`" to "`with validator version >= 1.8`"
The `m_ver.SkipDxilVersion(1, 8)` below is still correct to constrain for validator version.  However, the library target can be lower.

2023-06-30 22:02 UTC, tex3d commented on tools/clang/unittests/HLSL/DxilContainerTest.cpp
> +                                      L"lib_6_7", nullptr, 0, nullptr, 0,
This `lib_6_7` could be a lower library target, such as `lib_6_3` to ensure that we add the part on all down-level library targets, as long as validator version is high enough.

2023-07-06 22:06 UTC, bob80905 commented on lib/HLSL/DxilValidation.cpp
> +      if (ValCtx.isLibProfile) {
I've now changed the behavior so that an error is emitted if the part is detected in a non library blob.

2023-07-06 22:24 UTC, tex3d approved these changes
LGTM!

2023-07-06 22:35 UTC, tex3d commented on lib/DxilContainer/DxilContainerAssembler.cpp
> +    bool bValidatorAtLeast_1_8 = DXIL::CompareVersions(ValMajor, ValMinor, 1, 8) >= 0;
We already have `ValMajor` and `ValMinor` retrieved earlier, and used to initialize some bool variables there.  Can we just move the `bValidatorAtLeast_1_8` up with the others and remove the extra validator version retrieval here?

2023-07-06 22:49 UTC, tex3d commented on lib/DxilContainer/DxilContainerAssembler.cpp
> +
nit: there's some trailing whitespace on the prior line and an extra newline here.

2023-07-06 22:50 UTC, tex3d approved these changes
LGTM.

2023-07-10 17:50 UTC, python3kgae approved these changes

2023-07-10 18:01 UTC, merged